# This file generates the GitHub Actions matrix
---
include:

  # sweep
  - board: nice_nano_v2
    shield: sweep_central_dongle dongle_display
    artifact-name: sweep_central_dongle
  - board: nice_nano_v2
    shield: sweep_central_left
    artifact-name: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_peripheral_left 
    artifact-name: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_peripheral_right 
    artifact-name: sweep_peripheral_right
    
  #- board: nice_nano_v2
  #  shield: sweep_central_left 
  #  cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #  artifact-name: sweep_central_left_with_logging

  # reset
  - board: nice_nano_v2
    shield: settings_reset
